### ISSUE TITLE
srcset support

### ISSUE THREAD

**Issue by mrcsmcln** [imagekit-developer/imagekit-vuejs#11]
Hey there,

Just wondering if the IK team plans on supporting srcset with this component?

Thanks!

**Comment by imagekitio** [comment]
Hi @mrcsmcln 

Yes, we are planning to add support for `srcset` in the near future. Meanwhile, can you tell me how exactly do you expect this to work?

For example, if could you share the sample syntax and expected HTML and behavior, that would be helpful.

**Comment by mrcsmcln** [comment]
Of course. I could imagine `srcset` being dynamically generated based on one of two (but not both) attributes: `widths` and `densities`. It could look something like this:

```vue
<IKImage
  :widths="$options.widths"
  path="/path/to/my/image.png"
  tag="source" // bonus prop suggestion; default: 'img'
  type="webp"  // not a prop, just a passed attribute
/>
```

```js
export default {
  widths: [16, 32, 64, 128]
}
```

This would set width transformations: `w-16`, `w-32`, etc. Not sure whether `transformations` or `widths` should take precedence in the event of a conflict.

`densities` would similarly be an array, like `[1, 1.5, 2, 2.5, 3]`. This would override width transformations, but as a decimal: No width transformation for `3x`, `w-0.833` for `2.5x`, etc.

I _think_ this would work because `srcset` is not designed for art direction, since the browser automatically and opaquely selects an image source, and it's always based on width or pixel density.

If the developer wants to specify a custom `srcset`, then they can simply eschew `widths` and `densities` in favor of a `srcset` attribute that will passed down to the resulting `<img>` element. So some conditional logic would need to be implemented in `<IKImage>` to accomodate this behavior, but I think it's important should the developer want a truly custom `srcset` for some unforeseen reason. Perhaps `v-bind="attrs"`, where `attrs` is a computed property that sometimes includes a `srcset` property in the returned object.

As a side note, I feel like the onus for implementing `sizes` should be on the developer, unless you added that to `IKContext`, but that's beyond the scope of this issue and it's quite an assumption to make on the design side of things.

**Comment by imagekitio** [comment]
We have decided to not add support for `srcset` in any frontend SDKs because `srcset` alone won't be sufficient to implement [responsive images](https://imagekit.io/responsive-images/). SDK can never accurately generate `sizes` attribute values. Giving such partial support will create more confusion for developers leading to sub-optimal implemetation of responsive images in applications.

I agree with you that the onus of implementing responsive images is on the developer. The `srcset` and `sizes` attribute can be provided and will be used as it is. The URL generation utility of the underlying imagekit Javascript SDK can be used to generate the URL
